### ISSUE TITLE
Suggestion: hotkeys for desk positions

### ISSUE THREAD

**Issue by falkenhawk** [golota60/trayasen#16]
I'd be great if positions could be changed by pressing a defined key combination. Hotkeys should work globally, system-wide.

**Comment by golota60** [comment]
Thanks for the suggestion! I've been actually meaning to add that for a while, but first I want to [improve the stability of the app across systems](https://github.com/golota60/trayasen/issues/10) - this will be a major change so I'll try to add global hotkeys alongside it.

**Comment by falkenhawk** [comment]
@golota60 thank you for implementing this feature! 🙏 I have troubles of making them work on win10. Hotkeys are being registered, but some keys or combinations with ctrl / alt / win key do not work. E.g. a hotkey for just a single key, e.g. "R" - works. "/" - works on the regular "/" key (next to right-shift), does not work on numpad-"/" key. "Shift+R", "Control+R", "Shift+/", "Control+AltGraph+/", "Control+/", "Meta+/" - those do not work

**Comment by falkenhawk** [comment]
No problem, thanks for your commitment! I'll experiment with the values in config.
